
# Los tags se convierten en una definición de alto nievl de los tipos de operaciones que se van a realizar en el playbook:
# - instalacion:        Si quiero asegurar que el servidor web esté instalado y actualizado
# - configuracion:      Si quiero asegurar que el servidor web esté correctamente configurado
# - pruebas:            Si quiero asegurar que el servidor web esté funcionando correctamente
# - despliegue:         Si quiero asegurar que el servidor web esté desplegado correctamente

# Empezamos a plantear el playbook.
# Por ahora SOLO NOS PREOCUPAMOS DE LA ESTRUCTURA GENERAL DEL PLAYBOOK, y de ir identificando las tareas que necesitamos hacer.

- name:               Despliegue de servidor web Apache
  hosts:              all
  vars:               # CONSTANTES
      paquete: 
        redhat:       httpd
        ubuntu:       apache2
      dependencias:
        redhat:       
          - git
          - curl
        ubuntu:       
          - git
          - curl
  # become:         true    # Que para todas las tareas del playbook se aplique la elevación de privilegios automáticamente
                            # ESTO ES UNA GUARRADA Y PURA VAGANCIA. No toda tarea requiere privilegios de superusuario
                            # Es un potencial problema de seguridad, ya que cualquier tarea podría ejecutarse con privilegios elevados innecesariamente
                            # Esto no lo usamos. En cursos es muy cómodo. Y en muchos tutoriales de YOUTUBE lo vemos...
                            # En mi empresa ni de coña!
                            # Elevaré los permisos solo cuando sea estrictamente necesario, usando become en tareas individuales

  pre_tasks:
    - name:                 Obtener información previa a la ejecución del playbook
      block:
          
        - name:             Obtener información del sistema operativo del host destino
          tags:
            -               always

        - name:             Mirar si el repositorio existe
          # Comprobar que el repositorio existe. Si no existe corto la ejecución de playbook
          # Esta tarea quiero que siempre acabe en OK, tanto si el repositorio existe como si no existe
          # Si se puede ejecuatr curl, la tarea ha hecho su trabajo, que es MIRAR si existe
          register:         comprobacion_repositorio
          tags:
            -               despliegue

    - name:                 Validar condiciones previas antes de ejecutar el playbook
      block:
      - name:               Cortar la ejecución del playbook si el sistema operativo no es compatible
        when:               Cuando el sistema operativo no sea compatible
        tags:
          -                 always

      - name:               Cortar la ejecución del playbook si el repositorio no existe
        # Comprobar que el repositorio existe. Si no existe corto la ejecución de playbook
        when:               Si la tarea anterior(comprobacion_repositorio) me dice que el repo no existe                 
        tags:
          -                 despliegue

    - name:                 Preparativos previos para poder ejecutar el playbook
      block:
        - name:             Actualizar los repositorios con los últimos paquetes disponibles
          become:           true    # Para esta tarea necesitamos privilegios de superusuario
                                  # Necesito elevar privilegios del usuario para actualizar los repositorios
                                  # Qué formas hay de hacer eso en un Linux?
                                  # - sudo
                                  # - su - 
                                  # Esto se definirá en otro sitio.
                                  # Cuando configure (inventario) cómo conectar a una máquina, dire trambién qué mecanismo se utilizará para las elevaciones de privilegios
          changed_when:     false # Aunque se actualicen los repositorios, 
                                # no consideramos que el sistema haya cambiado desde el punto de vista de este playbook

        - name:             Asegurar que las dependencias del playbook están instaladas
          become:           true
          changed_when:     false # Aunque se instalen las dependencias, no consideramos que el sistema haya cambiado desde el punto de vista de este playbook
      tags:
        -                   always


  tasks:
    - name:    
      tags:
        -             

  post_tasks:
    - name:           Probar que el servidor contesta llamandolo por curl
      tags:
        -             pruebas

  handlers:
    - name:    
      listen: 
      tags:
        - 
