
# Los tags se convierten en una definición de alto nievl de los tipos de operaciones que se van a realizar en el playbook:
# - instalacion:        Si quiero asegurar que el servidor web esté instalado y actualizado
# - configuracion:      Si quiero asegurar que el servidor web esté correctamente configurado
# - pruebas:            Si quiero asegurar que el servidor web esté funcionando correctamente
# - despliegue:         Si quiero asegurar que el servidor web esté desplegado correctamente

# Empezamos a plantear el playbook.
# Por ahora SOLO NOS PREOCUPAMOS DE LA ESTRUCTURA GENERAL DEL PLAYBOOK, y de ir identificando las tareas que necesitamos hacer.

- name:               Despliegue de servidor web Apache
  hosts:              all
  #vars:               # CONSTANTES
      
  gather_facts:       false

  # become:           true    # Que para todas las tareas del playbook se aplique la elevación de privilegios automáticamente
                              # ESTO ES UNA GUARRADA Y PURA VAGANCIA. No toda tarea requiere privilegios de superusuario
                              # Es un potencial problema de seguridad, ya que cualquier tarea podría ejecutarse con privilegios elevados innecesariamente
                              # Esto no lo usamos. En cursos es muy cómodo. Y en muchos tutoriales de YOUTUBE lo vemos...
                              # En mi empresa ni de coña!
                              # Elevaré los permisos solo cuando sea estrictamente necesario, usando become en tareas individuales

  pre_tasks:
      
    - name:                 Pretareas para la ejecución del playbook
      ansible.builtin.include_tasks:
        file:                   "pre_tasks/main.yaml"
      tags:
        - always
  
  tasks:

    - name:                 Tareas del plabook
      ansible.builtin.include_tasks:
        file:                   "tasks/main.yaml"
      tags:
        - always

  post_tasks:
    # Cuando defino pruebas, quiero que sean ATOMICAS: Es decir, que cada prueba pruebe solo una cosa.
    # Es decir, que si la prueba falle, SEPA PERFECTAMENTE QUE HA FALLADO
    - name:           Verificar que el servicio de Apache está corriendo
      tags:
        -             pruebas

    - name:           Verificar que el apache ha levantado en el puerto adecuado
    # wait_for
      tags:
        -             pruebas

    - name:           Verificar que el puerto está abierto en el firewall
    # wait_for
      tags:
        -             pruebas
      ## telnet al puerto.. desde el nodo de control (desde fuera) a ver si llego al puerto
      ## HOST?        IP
      ##              example2.com? Y si está mal el DNS o no tengo reistrado ese nombre?
      ## PUERTO?      80

    - name:           Verificar que llego a la máquina vía domain (compruebo DNS)
    # ping NO ES LO SUYO
      # Este modulo no hace ping.. Se conecta a la máquina y mira siu puede ejecutar allí python
    # shell (y lanzo curl) PERO LO HACEMOS CON ESTE
      tags:
        -             pruebas

    - name:           Verificar que la web responde con el contenido que debe
    # uri                  
      tags:
        -             pruebas
      # haciendo curl.. o mejor usando un módulo de ansible que ya conocemos: uri
      # darme la url:   "http://example2.com:80/test"
      # Desde donde lanzo el CURL?
      # Desde el nodo remoto o desde el nodo de control?? Desde fuera... Desde el nodo de control
      # Pero las tareas del playbook dónde se ejecutan? EN EL REMOTO.
      # Esta tarea no querría que se ejecutase en el nodo remoto. El curl no quiero que se lance desde el nodo remoto
      # Quiero que se lanza desde el nodo de control.
      # Quiero que esta tarea se ejecute en el nodo de control.
      delegate_to: localhost
      # Me permite que una tarea no se ejecute en el nodo remoto, sino en el nodo que me interesa.


    #- name:          Si las pruebas van bien? Eliminar backups
    # Si la prueba va mal? Rollback? NO...
    # Si hay que hacer rollback... eso es otro trabajo.... que puede tener otras implicaciones.
    # Mi playbook INSTALA. SI FALLA AVISA!
    # Y ya otro se encargaré de lo que tenga que hacer: REPARTO DE TAREAS. Si no acabo con un playbook de cojones.
    # Eso si.. mi playbook , al instalar, por si falla, hace backups... para que el que venga detrás tenga de donde tirar!


    # AWX: Definiré un Workflow: Ejecute el playbook de instalar BBDD, Despues el Playbook de Apache + App. Si va mal El playbook de rollback...

  handlers:
    - name:                 Reiniciar Apache
      ansible.builtin.service:
        name:               "{{ nombre_paquete_apache[familia_sistema_operativo] }}"
        state:              restarted
      listen:               
        -                   CONFIGURACION_DE_APACHE_CAMBIADA
        -                   NUEVA_VERSION_APP_DESPLEGADA
      tags:
        -                   always


