
# Los tags se convierten en una definición de alto nievl de los tipos de operaciones que se van a realizar en el playbook:
# - instalacion:        Si quiero asegurar que el servidor web esté instalado y actualizado
# - configuracion:      Si quiero asegurar que el servidor web esté correctamente configurado
# - pruebas:            Si quiero asegurar que el servidor web esté funcionando correctamente
# - despliegue:         Si quiero asegurar que el servidor web esté desplegado correctamente

# Empezamos a plantear el playbook.
# Por ahora SOLO NOS PREOCUPAMOS DE LA ESTRUCTURA GENERAL DEL PLAYBOOK, y de ir identificando las tareas que necesitamos hacer.

- name:               Despliegue de servidor web Apache
  hosts:              all
  #vars:               # CONSTANTES
      
  gather_facts:       false

  # become:           true    # Que para todas las tareas del playbook se aplique la elevación de privilegios automáticamente
                              # ESTO ES UNA GUARRADA Y PURA VAGANCIA. No toda tarea requiere privilegios de superusuario
                              # Es un potencial problema de seguridad, ya que cualquier tarea podría ejecutarse con privilegios elevados innecesariamente
                              # Esto no lo usamos. En cursos es muy cómodo. Y en muchos tutoriales de YOUTUBE lo vemos...
                              # En mi empresa ni de coña!
                              # Elevaré los permisos solo cuando sea estrictamente necesario, usando become en tareas individuales

  pre_tasks:
      
    - name:                 Pretareas para la ejecución del playbook
      ansible.builtin.include_tasks:
        file:                   "pre_tasks/main.yaml"
      tags:
        - always
  
  tasks:

    - name:                 Tareas del plabook
      ansible.builtin.include_tasks:
        file:                   "tasks/main.yaml"
      tags:
        - always

  post_tasks:
    # Pruebas
    - name:           Probar que el servidor contesta llamandolo por curl
      tags:
        -             pruebas

    #- name:          Si las pruebas van bien? Eliminar backups
    # Si la prueba va mal? Rollback? NO...
    # Si hay que hacer rollback... eso es otro trabajo.... que puede tener otras implicaciones.
    # Mi playbook INSTALA. SI FALLA AVISA!
    # Y ya otro se encargaré de lo que tenga que hacer: REPARTO DE TAREAS. Si no acabo con un playbook de cojones.
    # Eso si.. mi playbook , al instalar, por si falla, hace backups... para que el que venga detrás tenga de donde tirar!


    # AWX: Definiré un Workflow: Ejecute el playbook de instalar BBDD, Despues el Playbook de Apache + App. Si va mal El playbook de rollback...

  handlers:
    - name:                 Reiniciar Apache
      ansible.builtin.service:
        name:               "{{ nombre_paquete_apache[familia_sistema_operativo] }}"
        state:              restarted
      listen:               
        -                   CONFIGURACION_DE_APACHE_CAMBIADA
        -                   NUEVA_VERSION_APP_DESPLEGADA
      tags:
        -                   always


