# Son archivos muy sencillos de crear. Nos encantan... aunque para entornos serios... no valen.

# Lo que ponemos es una línea por ENTORNO REMOTO, con la siguente sixtaxis:
# NOMBRE_ENTORNO_REMOTO  PROPIEDAD1=VALOR1  PROPIEDAD2=VALOR2 # Y así todas als propiedades que queramos definir

# Ansible usa ciertos nomrbe de propiedades por defecto.. para ciertas tareas:

# ansible_host   Contiene el fqdn o IP que se utiliza para conectar con el entorno remoto
#                Si no se pone, por defecto, toma el valor de NOMBRE_ENTORNO_REMOTO 
#                Ese nombre: NOMBRE_ENTORNO_REMOTO es al que desde los playbooks nos podemos referir como inventory_hostname

# ansible_connection  Define el tipo de conexión que Ansible debe usar para conectarse al entorno remoto.
#                     Por defecto, Ansible usa 'ssh'. Pero hay otras opciones:
#                       - local    (Si queremos ejecutar las tareas en el propio nodo de control)
#                       - ssh      (Por defecto, se usa SSH para conectarse al entorno remoto)
#                       - paramiko (Usa la biblioteca Paramiko para la conexión SSH, útil si no se dispone de un cliente SSH nativo)
#                       - winrm   (Usa Windows Remote Management para conectarse a entornos Windows)

# ansible_port      Especifica el puerto que Ansible debe usar para conectarse al entorno remoto.
#                   Por defecto, Ansible usa el puerto 22 para conexiones SSH.

# ansible_user      Especifica el usuario que Ansible debe usar para conectarse al entorno remoto.
#                   Por defecto, Ansible usa el usuario con el que se ejecuta el playbook.

# ansible_password  Especifica la contraseña que Ansible debe usar para conectarse al entorno remoto.
#                   Como podemos imaginar.. no es muy recomendable almacenar contraseñas en texto plano en los archivos de inventario.

# ansible_ssh_private_key_file  Especifica la ruta al archivo de clave privada que Ansible debe usar para la autenticación SSH.
#                   Evidentemente tampoco es recomendable almacenar rutas a claves privadas en texto plano en los archivos de inventario.

# Cuando ejecuto un playbook, tengo la opción de suministrar dinámicamente 
# ciertos valores de las propiedades de conexión mediante la línea de comandos,
# por ejemplo usando las opciones --user, --ask-pass, --private-key, etc.

# ansible_become     Especifica si Ansible debe usar privilegios elevados (sudo) al ejecutar tareas en el entorno remoto.
# ansible_become_method  Especifica el método que Ansible debe usar para obtener privilegios elevados.
#                        Por defecto, Ansible usa 'sudo'. Otras opciones incluyen 'su', 'pbrun', 'pfexec', etc.

# ansible_become_user  Especifica el usuario al que Ansible debe cambiar cuando utiliza privilegios elevados.
#                     Por defecto, Ansible usa el usuario 'root'.
# ansible_become_password  Especifica la contraseña que Ansible debe usar para obtener privilegios elevados.

mipc      ansible_host=localhost    ansible_connection=local   version_apache=1.42.7

# Los entornos remotos podemos AGRUPARLOS
#[NOMBRE_GRUPO]
[webservers]
el-webserver-de-produccion

[webservers:children]
nginx
apache

[apache]
apache.desa   ansible_host=apache.desa.miempresa.net   
apache.test   ansible_host=apache.test.miempresa.net   
apache.prod   ansible_host=apache.prod.miempresa.net   

[nginx]
nginx[01-20] 

[webservers:vars]
ansible_connection=ssh
ansible_user=miusuario

[apache:vars]
version_apache=1.42.7

# FACIL? SI! Muy sencillo de escribir y de leer.
# Qué tal se crean grupos?      CHUPAO!
# Qué tal se definien host?     REQUETE CHUPAO!
# Y definirles propiedades a los host? REQUETE REQUETE CHUPAO!

# Y entonces, por qué he dicho yo que esto no vale?
# Hay 2 problemas:

# Problema 1: En la empresa no tengo 5 servidores... tengo 2000 servidores.
# Un archivo para gobernarlos a todos? Quién le mete mano al archivo? Sauron? Quién se atreve?
# Además, que en la empresa normalmente tengo distintos departamentos... que organizan distintos grupos de servidores.
# Los de un dpto pueden ver/MODIFICAR los servidores de otros? Estamos locos?

# Problema 2: Variables/Propiedades
# Si quiero definir la propiedad/variable: version_apache=1.4.2 FACILITO! REQUETE REQUETE CHUPAO!
# Y si quiero definir la variable:

#aplicacion_a_desplegar:
#  repo_git:               https://github.com/usuario/repositorio.git
#  puerto_apache:          80
#  nombre_dominio:         example2.com
#  carpeta_despliegue:     /var/www/html/app1
#  configuracion_apache: |
#    # Aquí puedes añadir configuración adicional para el virtual host de Apache
#    # Por ejemplo:
#    <Directory /var/www/html/app1>
#        Options Indexes FollowSymLinks
#        AllowOverride All
#        Require all granted
#    </Directory>
#    ErrorLog ${APACHE_LOG_DIR}/error.log
#    CustomLog ${APACHE_LOG_DIR}/access.log combined
#  pruebas:
#    - url:                /test
#    - codido_estado:      200
#    - contenido:          Sistema funcionando

# EIN? UPS!!!! Ni de coña!
# Se puede...
# aplicacion_a_desplegar={repo_git: "https://github.com/usuario/repositorio.git", puerto_apache: 80, nombre_dominio: "example2.com", carpeta_despliegue: "/var/www/html/app1", configuracion_apache: "<Directory /var/www/html/app1>\n    Options Indexes FollowSymLinks\n    AllowOverride All\n    Require all granted\n</Directory>\nErrorLog ${APACHE_LOG_DIR}/error.log\nCustomLog ${APACHE_LOG_DIR}/access.log combined", pruebas: [{url: "/test", codido_estado: 200, contenido: "Sistema funcionando"}]}

# Esta bonito... pero no vale!
# Para un tutorial queda aparente
# Para una empresa es una ruina!
