aplicacion_a_desplegar:
  repo_git: "https://github.com/usuario/repositorio.git"
  puerto_apache: 80
  nombre_dominio: "example2.com"
  carpeta_despliegue: "/var/www/html/app1"
  configuracion_apache: |
    <Directory /var/www/html/app1>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
  pruebas:
    - url: "/test"
      codido_estado: 200
      contenido: "Sistema funcionando"
